title: "Efforting | Nathaniel Guy Mahieu"
description: >-
  I dredge dreams,
  try everything,
  and finish a thing or two.
baseurl: "n.mahi.eu"
repository: nathaniel-mahieu/n.mahi.eu.github.io
remote_theme: yousinix/portfolYOU
open_new_tab: false

plugins:
  - jemoji

nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**

author:
  name: Nathaniel Guy Mahieu
  image: https://n.mahi.eu/PXL_20250825_235941140.MP.jpg
  email: "n@mahi.eu"
  github: nathaniel-mahieu
  instagram: scalefreeself
  linkedin: nathaniel-g-mahieu
  stackoverflow: 3565544

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:            
    output: true       

disqus:
  shortname: your-short-name-disqus

analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id


buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:             
      path: ""         
      type: "elements" 
    values:            
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"